app:
  name: admin-demo-go
  mode: debug
  port: 8889
  jwt_secret: ""
  jwt_expire_hours: 24

mysql:
  dsn: "root:shatang@tcp(192.168.5.12:3306)/admin_demo?charset=utf8mb4&parseTime=True&loc=Local"
  database: "admin_demo"
  max_idle_conns: 10
  max_open_conns: 50
  conn_max_lifetime_minutes: 60

redis:
  addr: "192.168.5.12:6379"
  password: "shatang"
  db: 0

nsq:
  producer_addr: "192.168.5.12:4150"
  consumer_addr: "192.168.5.12:4160"
  topic: "admin_demo_events"
  channel: "admin_demo_channel"

storage:
  mode: "local" # local | aws-s3 | minio
  local:
    base_dir: "storage"
  s3:
    endpoint: "" # 可留空，默认 AWS S3 官方 endpoint
    access_key: ""
    secret_key: ""
    use_ssl: true
    public_bucket: ""
    private_bucket: ""
  minio:
    endpoint: "" # 例如 192.168.5.12:9000
    access_key: ""
    secret_key: ""
    use_ssl: false
    public_bucket: ""
    private_bucket: ""
  public:
    base_url: "" # 可选，公开下载链接域名，留空则用后端 /files/public/:name
